week5/week5_day2/RedditOnRails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create]
end

week5/week5_day2/RedditOnRails/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true

  belongs_to :author, foreign_key: :user_id, class_name: :User
  has_many :post_subs, dependent: :destroy, inverse_of: :post
  has_many :subs, through: :post_subs
  has_many :comments
end

week5/week5_day2/RedditOnRails/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_signed_in
  before_action :unless_author_or_mod, only: [:edit, :update, :destroy]
  before_action :must_have_sub, only: [:create, :update]

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to sub_url(@post.sub)
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

  def unless_author_or_mod
    @post = Post.find(params[:id])
    redirect_to sub_url(@post.sub) unless (current_user == @post.author || current_user == @post.sub.moderator)
  end

  def must_have_sub
    unless post_params[:sub_ids].length > 1
      if params[:aktion] == posts_url
        flash.now[:errors] = ["Must select at least 1 sub"]
        @post = Post.new(post_params)
        render :new
      else
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to subs_url
      end
    end
  end
end

week5/week5_day2/RedditOnRails/app/helpers/posts_helper.rb
module PostsHelper
end

week5/week5_day2/RedditOnRails/app/views/posts/_forms.html.erb
<form class="" action="<%= action %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method"
         value="<%= action == posts_url ? :post : :patch%>">
  <label>
    Title
    <input type="text" name="post[title]" value="<%= post.title %>">
  </label>
  <br>
  <label>
    URL
    <input type="text" name="post[url]" value="<%= post.url %>">
  </label>
  <br>
  <label>
    Content
    <textarea name="post[content]"><%= post.content %></textarea>
  </label>
  <br>
  <label>
    Subs
    <input type="hidden"
           name="post[sub_ids][]"
           value="">
    <% Sub.all.each do |sub| %>
      <br>
      <label>
        <input type="checkbox"
               name="post[sub_ids][]"
               value="<%=sub.id%>"
               <%= "checked" if post.subs.include?(sub) %> >
        <%= sub.title %>
      </label>
    <% end %>
  </label>
  <input type="hidden" name="aktion" value="<%= action %>">
  <br>
  <input type="submit"
        value="<%= action == posts_url ? "Create Post" : "Update Post"%>">
</form>

week5/week5_day2/RedditOnRails/app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%= render "forms", action: post_url(@post), post: @post %>

week5/week5_day2/RedditOnRails/app/views/posts/new.html.erb
<h2>New Post</h2>
<%= render "forms", action: posts_url, post: @post %>

week5/week5_day2/RedditOnRails/app/views/posts/show.html.erb
<%= link_to "All Subs", subs_url %>

<h2><%= @post.title %></h2>
<p><%= @post.url%></p>
<p><%= @post.content%></p>

<%= link_to "Edit Post", edit_post_url(@post) %>

<h3>Associated Subs</h3>
<% @post.subs.each do |sub| %>
<li><%= link_to sub.title, sub_url(sub) %></li>
<% end %>

<h2>Comments</h2>
<%= link_to "Comment on this post!", new_post_comment_url(@post) %>
<% @post.comments.where(parent_comment_id: nil).each do |comment| %>
<li><%= comment.content %></li>
<% end %>
<br>