week5/week5_day2/RedditOnRails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create]
end

week5/week5_day2/RedditOnRails/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text             not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator, foreign_key: :user_id, class_name: :User
  has_many :post_subs, dependent: :destroy, inverse_of: :sub
  has_many :posts, through: :post_subs
end

week5/week5_day2/RedditOnRails/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_signed_in
  before_action :unless_mod, only: [:edit, :update]

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id
    if @sub.save
      redirect_to subs_url
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub ||= Sub.find(params[:id])
    render :edit
  end

  def update
    @sub ||= Sub.find(params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def index
    @subs = Sub.all
    render :index
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy
    redirect_to subs_url
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def unless_mod
    @sub = Sub.find(params[:id])
    redirect_to sub_url(@sub) unless current_user == @sub.moderator
  end
end

week5/week5_day2/RedditOnRails/app/helpers/subs_helper.rb
module SubsHelper
end

week5/week5_day2/RedditOnRails/app/views/subs/_forms.html.erb
<form class="" action="<%= action %>" method="post">
  <%= auth_token %>
  <input type="hidden"
         name="_method"
         value="<%= action == subs_url ? :post : :patch %>">
  <label>
    Title
    <input type="text" name="sub[title]" value="<%= sub.title %>">
  </label>
  <label>
    Description
    <textarea name="sub[description]"><%= sub.description %></textarea>
  </label>

  <input type="submit"
         value="<%= action == subs_url ? "Create New Sub" : "Update Sub" %>">
</form>

week5/week5_day2/RedditOnRails/app/views/subs/_sub.html.erb
<li><%= link_to sub.title, sub_url(sub) %></li>

week5/week5_day2/RedditOnRails/app/views/subs/edit.html.erb
<h2>Edit Sub</h2>
<%= render "forms", action: sub_url(@sub), sub: @sub %>

week5/week5_day2/RedditOnRails/app/views/subs/index.html.erb
<h2>All Subs</h2>
<%= render @subs %>
<%= link_to "New Sub", new_sub_url %>
<%= link_to 'Add Post', new_post_url %>

week5/week5_day2/RedditOnRails/app/views/subs/new.html.erb
<h2>New Sub</h2>
<%= render "forms", action: subs_url, sub: @sub %>

week5/week5_day2/RedditOnRails/app/views/subs/show.html.erb
<h2><%=@sub.title%> sub forum</h2>
<p><%=@sub.description%></p>
<%= button_to "Delete Sub", sub_url(@sub), method: :delete %>

<%= link_to "Edit Sub", edit_sub_url(@sub) %>
<%= link_to "All Subs", subs_url %>

<%= link_to 'Add Post', new_post_url %>

<h3>Posts</h3>
<% @sub.posts.each do |post| %>
<li><%= link_to post.title, post_url(post)%></li>
<% end %>